# Generated by Django 5.1.4 on 2025-03-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_farmercrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmercrop',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
