# Generated by Django 5.1.4 on 2025-03-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_farmercrop_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmercrop',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
