# Generated by Django 5.1.4 on 2025-03-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_farmercrop_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmercrop',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
